[tool.poetry]
name = "project-py"
version = "0.1.0"
description = ""
authors = ["Di1nko <dena20035@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
